notifications:
  email:
    on_success: change # default: change
    on_failure: always # default: always

language: cpp
sudo: required
dist: trusty
os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

before_install:
  - export CC=gcc-5 && export CXX=g++-5
  - sudo apt-get -qq update

install:
  - time wget https://www.dropbox.com/s/yboqu7ufznmvy6l/ROOT-6.03.02_Python-2.7.tar.gz
  - time tar zxf ROOT-6.03.02_Python-2.7.tar.gz
  - mv ROOT-6.03.02_Python-2.7/root .
  - source root/bin/thisroot.sh

after_script:
  - root-config --features
