notifications:
  email:
    on_success: change # default: change
    on_failure: always # default: always

language: cpp
sudo: required
dist: trusty
os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

before_install:
  - export CC=gcc-5 && export CXX=g++-5
  - gcc-5 --version
  - sudo apt-get -qq update
  - git clone https://github.com/unittest-cpp/unittest-cpp.git
  - cd unittest-cpp/builds/
  - cmake ../
  - sudo make -j4 install
  - cd ../../

install:
  - time wget --no-check-certificate https://drive.google.com/open?id=0B_XQp_kYuMwQSzZERGZyVkdCM3c
  - time tar zxf ROOT-6.03.02_Python-2.7_GCC-4.8_x86_64.tar.gz
  - mv ROOT-6.03.02_Python-2.7_GCC-4.8_x86_64 root
  - source root/bin/thisroot.sh

after_script:
  - root-config --features
