notifications:
  email:
    on_success: change # default: change
    on_failure: always # default: always

language: cpp
sudo: required
dist: trusty
os: linux
services:
  - docker
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

before_install:
  - sudo apt-get -qq update
  - export CC=gcc-5 && export CXX=g++-5
  - docker pull rootproject/root-ubuntu16

install:
  - git clone https://github.com/unittest-cpp/unittest-cpp.git
  - cd unittest-cpp/builds/
  - cmake ../
  - sudo make -j4 install
  - cd ../../

before_script:
  - mkdir build
  - cd build
  - cmake ../

script:
  - make -j4
  - ./tests/unittest

after_script:
  - cd ../
  - rm -rf build
