notifications:
  email:
    on_success: change # default: change
    on_failure: always # default: always

language: cpp
sudo: required
dist: trusty
os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

before_install:
  - export CC=gcc-5 && export CXX=g++-5
  - sudo apt-get -qq update

install:
  - time wget https://www.dropbox.com/s/vvk21n6uj45bg0x/root-v6-09-02-760-g97cc38c.tbz
  - time tar xjf root-v6-09-02-760-g97cc38c.tbz
  - mv ./opt/root /opt
  - source /opt/root/v6-09-02-760-g97cc38c/bin/thisroot.sh
  - root-config --features
  - git clone https://github.com/unittest-cpp/unittest-cpp.git
  - cd unittest-cpp/builds/
  - cmake ../
  - sudo make -j4 install
  - cd ../../

before_script:
  - mkdir build
  - cd build
  - cmake ../

script:
  - make -j4
  - ./tests/unittest

after_script:
  - cd ../
  - rm -rf build
