env:
  global:
    - MAKEFLAGS="-j 5"
language: cpp
sudo: required
dist: trusty
os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - gfortran-5
      - gsl-bin
      - libgsl0-dev
      - lib64ncurses5-dev

env:
  global:
    - MAKEFLAGS="-j 5"

install:
  - docker run --name ub16 -idv ${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR} rootproject/root-ubuntu16

script: docker exec ub16 bash ${TRAVIS_BUILD_DIR}/.travis-script.sh  
