env:
  global:
    - MAKEFLAGS="-j 8"
language: cpp
sudo: required

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - gsl-bin
            - libgsl0-dev
            - libncurses5-dev
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - gsl-bin
            - libgsl0-dev
            - libncurses5-dev
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
  - sudo apt-get -qq update --install-suggests
  - eval "${MATRIX_EVAL}"
  - git clone https://github.com/unittest-cpp/unittest-cpp.git && cd unittest-cpp/builds/
  - cmake ../ && sudo make install && cd ../../
  - git clone https://github.com/spaulaus/xia-api.git && cd xia-api
  - mkdir build && cd build && cmake ../ -DCMAKE_INSTALL_PREFIX=/opt && make install && cd ../../
  - ln -s /opt/xia/api /opt/xia/current
  - git clone -b dev https://github.com/spaulaus/paass-laughing-conqueror.git && cd paass-laughing-conqueror
  - mkdir paass-build && mkdir install
  - cd paass-build && cmake ../ -DPAASS_BUILD_TESTS=TRUE -DPAASS_USE_ROOT=OFF && make install
  - cd ../install/bin/unittests/
  - (for test in *; do echo $test; ./$test; if [ $? != 0 ]; then false; exit; fi; done)

#install:
#  - docker run --name ub16 -idv ${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR} rootproject/root-ubuntu16

#script: 
#  - docker exec ub16 bash ${TRAVIS_BUILD_DIR}/.travis-script.sh  
