env:
  global:
    - MAKEFLAGS="-j 5"
language: cpp
sudo: required
dist: trusty
os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - gfortran-5
      - gsl-bin
      - libgsl0-dev
      - lib64ncurses5-dev

env:
  global:
    - MAKEFLAGS="-j 5"

before_install:
  - export CC=gcc-5 && export CXX=g++-5 && export FC=gfortran-5
  - sudo apt-get -qq update --install-suggests
  - mkdir -p /opt
  - git clone https://github.com/unittest-cpp/unittest-cpp.git && cd unittest-cpp/builds/
  - cmake ../ && sudo make -j4 install && cd ../../
  - git clone https://github.com/spaulaus/xia-api.git && cd xia-api
  - mkdir build && cd build && cmake ../ -DCMAKE_INSTALL_PREFIX=/opt && make install && cd ../../
  - ln -s /opt/xia/api /opt/xia/current
  - git clone https://github.com/spaulaus/paass-laughing-conqueror.git && cd paass-laughing-conqueror
  - git checkout dev
  - mkdir paass-build && cd paass-build
  - cmake ../ -DPAASS_BUILD_SCAN_UTILITIES=ON -DPAASS_BUILD_ACQ=ON -DPAASS_BUILD_TESTS=ON -DPAASS_BUILD_UTKSCAN=ON -DPAASS_USE_ROOT=OFF
  - make -j8 install
  - (for test in ../install/bin/unittests/*; do ./$test; if [ $? != 0 ]; then false; exit; fi; done)
  - cd .. && mkdir paass-build-all-flags && cd paass-build-all-flags
  - cmake ../ -DPAASS_BUILD_SCAN_UTILITIES=ON -DPAASS_BUILD_ACQ=ON -DPAASS_BUILD_TESTS=ON -DPAASS_BUILD_UTKSCAN=ON -DPAASS_USE_ROOT=OFF -DPAASS_UTKSCAN_GAMMA_GATES=ON -DPAASS_UTKSCAN_ONLINE=ON -DPAASS_UTKSCAN_TREE_DEBUG=ON -DPAASS_UTKSCAN_VERBOSE=ON
  - make -j8

script:
  - make -j8 install
  - cd ../install/bin/unittests
  - (for test in *; do ./$test; if [ $? != 0 ]; then false; exit; fi; done)
  
