notifications:
  email:
    on_success: change # default: change
    on_failure: always # default: always

language: cpp
sudo: required
dist: trusty
os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

before_install:
  - export CC=gcc-5 && export CXX=g++-5
  - sudo apt-get -qq update
  - git clone https://github.com/unittest-cpp/unittest-cpp.git
  - cd unittest-cpp/builds/
  - cmake ../
  - sudo make -j4 install
  - cd ../../

install:
  - ROOT_BUILD=ROOT-6.03.02_Python-${TRAVIS_PYTHON_VERSION}_GCC-4.8_x86_64
  - time wget --no-check-certificate https://copy.com/rtIyUdxgjt7h/ci/root_builds/${ROOT_BUILD}.tar.gz
  - time tar zxf ${ROOT_BUILD}.tar.gz
  - mv ${ROOT_BUILD} root
  - source root/bin/thisroot.sh

after_script:
  - root-config --features
